### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Pau-Marin** [Pau-Marin/Portfolio-Site#4]
# Site's roadmap
This issue will be a task list with all the features I plan to add.

## v1.0
- [x] Basic single page portfolio. (Done with #1 )

## v1.1
- [x] #5 (Done with #18)

## v1.2
- [ ] #19

## v1.3
- [ ] Add backend.
- [ ] Store data on a DDBB.

## v1.4
- [ ] Add project page.

## v2.0
- [ ] Add Three.js animations.

## v2.1
- [ ] Localization (Page loads in English/Spanish/French/Catalan based on user's location).
